"""remove department from orders

Revision ID: 000e04a0b036
Revises: 60cb8f90adf6
Create Date: 2026-05-29 11:16:38.444613
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '000e04a0b036'
down_revision: Union[str, None] = '60cb8f90adf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
