"""Add shipping columns to Order

Revision ID: 60cb8f90adf6
Revises: c593a1a18bbc
Create Date: 2026-05-28 10:02:21.714191
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '60cb8f90adf6'
down_revision: Union[str, None] = 'c593a1a18bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('courier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'courier')
    op.drop_column('orders', 'tracking_id')
    # ### end Alembic commands ###
