"""Add department to Category and Order

Revision ID: c593a1a18bbc
Revises: 969bc3de34df
Create Date: 2026-05-28 09:46:12.001727
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c593a1a18bbc'
down_revision: Union[str, None] = '969bc3de34df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('department', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'department')
    op.drop_column('categories', 'department')
    # ### end Alembic commands ###
