"""Add shipping_cost and tax_amount to orders

Revision ID: f7a8b9c0d1e2
Revises: a1b2c3d4e5f6
Create Date: 2026-05-31 10:05:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f7a8b9c0d1e2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'shipping_cost')
    # ### end Alembic commands ###
